[package]
name = "tictac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
symbol-map = "1.0.2"
multimap = "0.8.3"
strum = "0.24.1"
strum_macros = "0.24.0"